test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

google:
  service: GCS
  credentials:
    type: "service_account"
    project_id: "the-cat-factory"
    private_key_id: <%= Rails.application.credentials.dig(:gcs, :private_key_id) %>
    private_key: <%= Rails.application.credentials.dig(:gcs, :private_key).dump %>
    client_email: "the-cat-factory-rails@the-cat-factory.iam.gserviceaccount.com"
    client_id: "101933167458688231147"
    auth_uri: "https://accounts.google.com/o/oauth2/auth"
    token_uri: "https://accounts.google.com/o/oauth2/token"
    auth_provider_x509_cert_url: "https://www.googleapis.com/oauth2/v1/certs"
    client_x509_cert_url: "https://www.googleapis.com/robot/v1/metadata/x509/the-cat-factory-rails%40the-cat-factory.iam.gserviceaccount.com"
  project: "the-cat-factory"
  bucket: "the-cats"
